---
title: "Week 3 Assignment"
author: "Michael D'Acampora"
date: "September 15, 2017"
output: pdf_document
---


###1. Use the tools of this chapter to rearrange the vector sot hat all elements conform to the standard first_name last_name

```{r}
library('stringr')
library('tidyr')
```

```{r}
raw.data <-"555-1239Moe Szyslak(636) 555-0113Burns, C. Montgomery555-6542Rev. Timothy Lovejoy555 8904Ned Flanders636-555-3226Simpson,Homer5553642Dr. Julius Hibbert"

```

```{r}
name <- unlist(str_extract_all(raw.data, "[[:alpha:]., ]{2,}"))
name

phone <- unlist(str_extract_all(raw.data, "\\(?(\\d{3})?\\)?(-| )?\\d{3}(-| )?\\d{4}"))
```

```{r}
# removes the prefix from anyone who has one
pop.prefix <- str_trim(sub("[[:alpha:]]{1,}\\.", "" ,name))
pop.prefix

```

```{r}
# To switch the names 
fix.homer <-  sub('^(.*),Homer', 'Homer \\1', pop.prefix) 

fix.burns <- sub('^(.*),  Montgomery', 'Montgomery \\1', fix.homer)

clean.names <- fix.burns

df2 <- data.frame(Name=clean.names, Phone=phone)
df2
```

```{r}
# Splits the name column to first, last name 
extract(df2, Name, into=c('FirstName', 'LastName'), '(.*)\\s+([^ ]+)$')
```


###(b) Construct a logical vector indicating whether a character has a title (i.e., Rev. and Dr.).
```{r}

prefix <- str_detect(name,"[A-Za-z]{2,}\\.")
prefix
```

```{r}
#Applying same regex as before but including the "C." in Montgomery Burns
fix1 <-  sub('^(.*),Homer', 'Homer \\1', name) 

fix2 <- sub('^(.*), C. Montgomery', 'C. Montgomery \\1', fix1)

data.frame(Name=fix2, Title=prefix)
```

###(c) Construct a logical vector indicating whether a character has a second name.
```{r}
# I changed the params to only pop "Rev." and "Dr."
pop.prefix2 <- str_trim(sub("[[:alpha:]]{2,}\\.", "" ,fix2))

find_middle <- str_detect(pop.prefix2,"\\s[A-Za-z]{2,}\\ ")

df <- data.frame(Name=pop.prefix2, Middle_Name=find_middle)

df
```















